env:
  es6: true
  node: true
  mocha: false
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2017
plugins:
  - '@typescript-eslint'
rules:
  no-await-in-loop: off
  no-compare-neg-zero: error
  no-template-curly-in-string: error
  no-unsafe-negation: error
  valid-jsdoc:
    - warn
    - prefer:
        arg: param
        return: returns
      preferType:
        Boolean: boolean
        Number: number
        object: Object
        String: string
      requireReturn: false
      requireReturnType: true
      requireParamDescription: false
      requireReturnDescription: false
      requireParamType: true
  accessor-pairs: warn
  array-callback-return: error
  complexity:
    - off
    - max: 25
  consistent-return: warn
  curly:
    - error
    - multi-line
    - consistent
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  no-console:
    - error
    - allow:
        - warn
  no-empty-function: error
  no-floating-decimal: error
  no-implied-eval: error
  no-invalid-this: error
  no-lone-blocks: error
  no-new-func: error
  no-new-wrappers: error
  no-new: error
  no-octal-escape: error
  no-return-assign: off
  no-return-await: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-useless-call: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-warning-comments: warn
  prefer-promise-reject-errors: error
  require-await: warn
  wrap-iife: error
  yoda: error
  no-label-var: error
  no-undef-init: error
  callback-return: error
  handle-callback-err: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  capitalized-comments:
    - error
    - always
    - ignoreConsecutiveComments: true
  consistent-this:
    - error
    - '$this'
  func-names: error
  func-name-matching: error
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  max-depth: error
  max-nested-callbacks:
    - error
    - max: 4
  new-cap: off
  no-array-constructor: error
  no-inline-comments: error
  no-lonely-if: error
  no-mixed-operators: error
  no-new-object: error
  no-unneeded-ternary: error
  nonblock-statement-body-position: error
  operator-assignment: error
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  unicode-bom: error
  no-duplicate-imports: error
  no-useless-computed-key: error
  no-useless-constructor: error
  prefer-arrow-callback: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/class-name-casing': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-shadow': error
